added two smart bee designs boards
adafruit/tinyuf2 pull request #237
Opened 2022-08-07 16:01 UTC by strid3r21

first time posting a PR in this repo so please let me know if im missing anything or need to change/add more.

thanks

2022-08-09 07:26 UTC, hathach reviewed
thank for the pr, please
- correct the board id
- also add your board to ci build https://github.com/adafruit/tinyuf2/blob/master/.github/workflows/build_esp32.yml

2022-08-09 07:26 UTC, hathach commented on ports/espressif/boards/smartbeedesigns_bee_motion_s3/board.h
> +#define UF2_BOARD_ID      "Bee-Motion-S3-v1.0"
Board ID must follow the syntax of https://github.com/microsoft/uf2 check other board for reference

2022-08-09 14:31 UTC, hathach requested changes
please revert the unnecessary white space changes to the yml file.

2022-08-09 17:37 UTC, strid3r21 commented
i think its fixed. prettier was adding the additional white spaces when I saved the file.

2022-08-10 04:48 UTC, hathach requested changes
again, please revert the unnecessary changes to the yml file. Don't edit the whole file, you only need to add your board to the list in ABC order.

2022-08-10 04:55 UTC, strid3r21 commented
> again, please revert the unnecessary changes to the yml file. Don't edit the whole file, you only need to add your board to the list in ABC order.

What changes are you referring to? All ive done is add my two boards to the list. I thought you were originally referring to the indention being different from the master, but now I'm not sure what you're talking about.

2022-08-10 04:57 UTC, hathach commented
> > again, please revert the unnecessary changes to the yml file. Don't edit the whole file, you only need to add your board to the list in ABC order.
> 
> What changes are you referring to? All ive done is add my two boards to the list. I thought you were originally referring to the indention being different from the master, but now I'm not sure what you're talking about.

there is the "File Changes" tab in the top of the PR, you should always double check that.

2022-08-10 05:10 UTC, strid3r21 commented
> > > again, please revert the unnecessary changes to the yml file. Don't edit the whole file, you only need to add your board to the list in ABC order.
> > 
> > What changes are you referring to? All ive done is add my two boards to the list. I thought you were originally referring to the indention being different from the master, but now I'm not sure what you're talking about.
> 
> there is the "File Changes" tab in the top of the PR, you should always double check that.

Oh I think i see what's wrong now. I'll try and fix it in a few hours once I'm home..sorry for the hassle.

2022-08-10 08:20 UTC, closed without merging