i.MX RT: Allow per-board custom init hook
adafruit/tinyuf2 pull request #301
Opened 2023-03-07 22:08 UTC by ccrome

## Checklist
- [x] Please provide specific title of the PR describing the change
- [x] Please provide related links (*eg. Issue which will be closed by this Pull Request*)

-----------

## Description of Change
Some custom i.MX boards require per board setup.  Currently, I don't see a mechanism for a specific board to have a setup call.

As a specific example, For example, on the i.MX RT 1011, if you happen to have the boot LED on `GPIO_AD_02`, you might need to custom configure `GPR26` in order for it to work with the GPIO configuration you want to use.   

Additionally, there are lots of other potential reasons you might want to do some setup in `boards/<board_name>`.

This patch adds `#ifdef BOARD_INIT_POST_HOOK `, and if it's defined, then `board_init_post_hook()` will be called at the end of `board_init()`.

2023-03-09 04:55 UTC, ccrome commented
It does beg the question, are there other places where there should be custom hooks on a per-board basis?

2023-03-09 08:53 UTC, hathach commented
we add an optional API (weak function) to board_api.h e.g `board_init_post()` in conjunction with board_teardown_post()

2023-03-09 18:38 UTC, ccrome commented
I updated the hooks to be in main now, rather than in the port directory.  Now it's easy for any board anywhere to define the functions to do per board custom stuff.

```
void board_init_post(void) __attribute__ ((weak));
void board_teardown_post(void) __attribute__ ((weak));
bool board_app_valid_post() __attribute__ ((weak));
```

2023-03-10 06:08 UTC, hathach requested changes
Please follow review for suggested change. Also I changed my mind on the naming, please change these _post to simply
- board_init2()
- board_teardown2()
- board_app_valid2()

2023-03-10 06:08 UTC, hathach commented on src/main.c
> +  bool valid = board_app_valid();
should be
```C
if ( !board_app_valid() ) return true;
if ( board_app_valid_post && !board_app_valid_post() ) return true;
```

2023-03-10 12:39 UTC, ccrome commented
I think I've got it all.  Thanks!

2023-03-10 13:31 UTC, hathach approved these changes
all good, thank you for your PR

2023-03-10 13:31 UTC, merged