Add ES3ink board
adafruit/tinyuf2 pull request #331
Opened 2023-06-29 22:06 UTC by dronecz

## Checklist

*By completing this PR sufficiently, you help us to review this Pull Request quicker and also help improve the quality of Release Notes*

- [x] Please provide specific title of the PR describing the change
- [x] If you are adding an new boards, please make sure
  - [x] Provide link to your allocated VID/PID if applicable
  - [x] Add your board to [action ci](/.github/workflows) in correct workflow and alphabet order for release binary
  - [x] `UF2_BOARD_ID` in your board.h follow correct format from [uf2 specs](https://github.com/microsoft/uf2#files-exposed-by-bootloaders)

-----------

## Description of Change

Add ES3ink board

2023-07-07 10:49 UTC, hathach requested changes
Please follow the PR template description and make following changes
- UF2_BOARD_ID is not correct
- remove adafruit favicon
- provide link to vid/pid

2023-07-07 11:02 UTC, dronecz commented
> Please follow the PR template description and make following changes
> 
> * UF2_BOARD_ID is not correct
> * remove adafruit favicon
> * provide link to vid/pid

I added link for VID/PID to PR comment and fixed issues which you mentioned. Thanks

2023-07-07 11:07 UTC, hathach commented
> I added link for VID/PID to PR comment and fixed issues which you mentioned. Thanks

your PID PR is still opened, have you allocated with the PID yet ?

2023-07-07 11:41 UTC, dronecz commented
> your PID PR is still opened, have you allocated with the PID yet ?

Sorry, I do not now what you mean by that. Could you rephrase your question? Thanks

2023-07-07 11:42 UTC, hathach commented
sorry, I mean did your request for the PID is accepted yet ?

2023-07-07 11:49 UTC, dronecz commented
No, I'm waiting for somebody to make a review, but I do not expect to be declined. I understand if you want wait until will be accepted.

2023-07-07 12:41 UTC, hathach commented
> No, I'm waiting for somebody to make a review, but I do not expect to be declined. I understand if you want wait until will be accepted.

PID approval is mandatory, I will mark this PR as draft for now. Please mark it as ready when you have PID allocated.

2023-07-20 04:41 UTC, lyusupov commented
> > your PID PR is still opened, have you allocated with the PID yet ?
> 
> Sorry, I do not now what you mean by that. Could you rephrase your question? Thanks

https://github.com/espressif/usb-pids

2023-09-12 05:37 UTC, hathach approved these changes
look good, thank you

2023-09-12 05:37 UTC, merged