esp23 fix README.md reboot_to_uf2
adafruit/tinyuf2 pull request #365
Opened 2023-12-04 08:50 UTC by s-light

## Description of Change

*fixes* the example in the *usage* section in the README.md for the expressif borads - 
as at least i needed a static cast to `esp_reset_reason_t` to compile cleanly..

2023-12-14 11:18 UTC, hathach approved these changes
look good, thank you

2023-12-14 11:20 UTC, hathach requested changes
please change to C style cast, since static_cast is C++ only and application code may be pure C

2023-12-14 19:44 UTC, s-light commented
done.

2023-12-15 03:42 UTC, hathach approved these changes
perfect, thank you

2023-12-15 03:43 UTC, merged